FROM eclipse-temurin

#COPY ./kafka_2.13-3.2.1.tgz ./kafka.tgz

RUN curl https://archive.apache.org/dist/kafka/3.2.1/kafka_2.13-3.2.1.tgz --output kafka.tgz

RUN mkdir kafka
RUN tar -xvzf kafka.tgz --strip-components=1 -C ./kafka
RUN rm kafka.tgz

COPY ./start-source.sh ./start-source.sh
RUN chmod 755 ./start-source.sh
CMD ./start-source.sh
