version: '3.8'
services:

  zookeeper-1:
    container_name: zookeeper-1
    image: zookeeper:1
    ports:
      - 2181:2181
    build:
      context: ./img/zookeeper
    volumes:
    - ./config/zoo/zookeeper.properties:/kafka/config/zookeeper.properties
  
  kafka1:
    container_name: kafka1
    image: kafka:1
    ports:
      - 9092:9092
    build: 
      context: ./img/kafka
    volumes:
    - ./config/brokers/b1/server.properties:/kafka/config/server.properties
    - ./data/kafka-1/:/tmp/kafka-logs/

  kafka2:
    container_name: kafka2
    image: kafka:1
    ports:
      - 9093:9092
    build: 
      context: ./img/kafka
    volumes:
    - ./config/brokers/b2/server.properties:/kafka/config/server.properties
    - ./data/kafka-2/:/tmp/kafka-logs/
  
  kafka3:
    container_name: kafka3
    image: kafka:1
    ports:
      - 9094:9092
    build: 
      context: ./img/kafka
    volumes:
    - ./config/brokers/b3/server.properties:/kafka/config/server.properties
    - ./data/kafka-3/:/tmp/kafka-logs/