version: '3.8'
services:

  zoo1:
    container_name: zoo1
    image: almost/zookeeper
    ports:
      - 2181:2181
    build:
      context: ./img/zookeeper
    volumes:
    - ./config/zoo/z1/zookeeper.properties:/kafka/config/zookeeper.properties
    - ./config/zoo/z1/myid:/tmp/zookeeper/myid
    - ./data/zoo-1/:/tmp/zookeeper/
  
  zoo2:
    container_name: zoo2
    image: almost/zookeeper
    ports:
      - 2182:2182
    build:
      context: ./img/zookeeper
    volumes:
    - ./config/zoo/z2/zookeeper.properties:/kafka/config/zookeeper.properties
    - ./config/zoo/z2/myid:/tmp/zookeeper/myid
    - ./data/zoo-2/:/tmp/zookeeper/

  zoo3:
    container_name: zoo3
    image: almost/zookeeper
    ports:
      - 2183:2183
    build:
      context: ./img/zookeeper
    volumes:
    - ./config/zoo/z3/zookeeper.properties:/kafka/config/zookeeper.properties
    - ./config/zoo/z3/myid:/tmp/zookeeper/myid
    - ./data/zoo-3/:/tmp/zookeeper/
    
  kafka1:
    container_name: kafka1
    image: almost/kafka
    ports:
      - 9092:9092
      - 29092:29092
    build: 
      context: ./img/kafka
    volumes:
    - ./config/brokers/b1/server.properties:/kafka/config/server.properties
    - ./data/kafka-1/:/tmp/kafka-logs/
    - ./data/source/:/home

  kafka2:
    container_name: kafka2
    image: almost/kafka
    ports:
      - 9093:9093
      - 29093:29093
    build: 
      context: ./img/kafka
    volumes:
    - ./config/brokers/b2/server.properties:/kafka/config/server.properties
    - ./data/kafka-2/:/tmp/kafka-logs/

  kafka3:
    container_name: kafka3
    image: almost/kafka
    ports:
      - 9094:9094
      - 29094:29094
    build: 
      context: ./img/kafka
    volumes:
    - ./config/brokers/b3/server.properties:/kafka/config/server.properties
    - ./data/kafka-3/:/tmp/kafka-logs/

  source:
    container_name: source
    image: almost/source
    ports:
      - 8001:8001
    build: 
      context: ./img/connect/source
    volumes:
    - ./config/sources/connect-standalone.properties:/kafka/config/connect-standalone.properties
    - ./config/sources/connect-file-source.properties:/kafka/config/connect-file-source.properties
    - ./data/source/:/home/

  sink:
    container_name: sink
    image: almost/sink
    ports:
      - 8002:8002
    build: 
      context: ./img/connect/sink
    volumes:
    - ./config/sink/connect-standalone.properties:/kafka/config/connect-standalone.properties
    - ./config/sink/connect-file-sink.properties:/kafka/config/connect-file-sink.properties
    - ./data/sink/:/home/



  kafdrop:
    image: 'obsidiandynamics/kafdrop:latest'
    restart: "no"
    ports:
      - 9000:9000
    
    environment:
      - KAFKA_BROKERCONNECT=kafka1:29092,kafka2:29093,kafka3:29094
      - JVM_OPTS=-Xms32M -Xmx64M
      - SERVER_SERVLET_CONTEXTPATH=/
    
    container_name: kafdrop
    depends_on:
      - "kafka1"
      - "kafka2"
      - "kafka3"


